# Generated by Django 3.2 on 2024-08-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='titles', to='reviews.category'),
        ),
    ]
